version: '3'
services:
  rethinkdb:
    container_name: tw-bot-rethinkdb
    image: rethinkdb
    ports:
      - 28015:28015
  bot:
    container_name: tw-bot
    build: .
    depends_on:
      - rethinkdb
