version: '3'
services:
  rethinkdb:
    container_name: tw-bot-rethinkdb
    image: rethinkdb
    ports:
      - 28015:28015
  bot:
    container_name: tw-bot
    build: .
    enviroment:
      - telegram.token=token
      - telegram.error.admin=0000000
      - darksky.token=
      - google.geocoding.token=
    links:
      - rethinkdb
